Create makefile
PinE-academy/DV_6_C_CPP pull request #10
Opened 2021-09-28 19:05 UTC by Shamikh91

2021-10-08 08:16 UTC, aloknigam247 requested changes

2021-10-08 08:16 UTC, aloknigam247 commented on shamikh/bit_array/makefile
> +demo: main.o b_array.o binary.h
what is binary.h here

2021-10-08 09:00 UTC, Shamikh91 commented
Sorry, that is a mistake. I meant to write b_array.h

2021-10-08 13:02 UTC, aloknigam247 requested changes

2021-10-08 13:02 UTC, aloknigam247 commented on shamikh/bit_array/makefile
> +demo: main.o b_array.o binary.h
even if its a b_array.h, then do we need b_array.h here. if b_array.h is changed then main.o and b_array.o will also update which will update demo too

2021-10-14 07:54 UTC, aloknigam247 requested changes

2021-11-16 15:50 UTC, merged