Create Makefile
PinE-academy/DV_6_C_CPP pull request #11
Opened 2021-09-28 19:05 UTC by sachhidanandjha

2021-10-05 06:48 UTC, aloknigam247 commented on Sachhidanand/bit_array/Makefile
> +//*****Makefile for bit_array*****
Makefile comments starts with #

2021-10-05 06:48 UTC, aloknigam247 commented on Sachhidanand/bit_array/Makefile
> +bit_array: main.o b_array.o b_array.h
output name should be demo
array.h is not needed here

2021-10-05 10:43 UTC, aloknigam247 requested changes

2021-10-05 10:43 UTC, aloknigam247 commented on Sachhidanand/bit_array/definition.c
> +void b_create(int size_t){
size_t is the type and not the variable name,
```suggestion
void b_create(size_t size){
```

2021-10-05 10:43 UTC, aloknigam247 commented on Sachhidanand/bit_array/definition.c
> +    int *array;
is int correct here, what if my number of bits is 1. then how many bits will we waste. should we take another type ?

2021-10-05 10:43 UTC, aloknigam247 commented on Sachhidanand/bit_array/definition.c
> +        }
we do not want to take input from user here

2021-10-05 11:24 UTC, sachhidanandjha commented on Sachhidanand/bit_array/definition.c
> +    int *array;
should we take unsigned char then?

2021-10-05 11:27 UTC, sachhidanandjha commented on Sachhidanand/bit_array/definition.c
> +void b_create(int size_t){
okay sir

2021-10-07 10:07 UTC, aloknigam247 commented on Sachhidanand/bit_array/definition.c
> +}b_array;
```suggestion
typedef struct
{
    unsigned char *array;
    unsigned int size;
} barray;
```

2021-10-08 08:55 UTC, aloknigam247 commented on Sachhidanand/bit_array/b_array.c
> +        free(arr);
what if user by mistake calls b_destroy again with same pointer ?

2021-10-08 12:52 UTC, aloknigam247 commented on Sachhidanand/bit_array/b_array.c
> +    if(arr)
do we need this if ? If line 49 is false then line 54 is obviously true

2021-11-16 08:05 UTC, merged