add Makefile
PinE-academy/DV_6_C_CPP pull request #5
Opened 2021-09-27 06:12 UTC by utkarshtyagi2

created make file initial commit

2021-10-04 14:36 UTC, aloknigam247 commented on Utkarsh/wcomp/Makefile
> +output:main.o strict.o fuzzy.o pattern.o
default output file should wcomp and not output

2021-10-04 16:40 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/Makefile
> +output:main.o strict.o fuzzy.o pattern.o
okay

2021-10-05 10:35 UTC, aloknigam247 requested changes

2021-10-05 10:35 UTC, aloknigam247 commented on Utkarsh/wcomp/main.c
> +            char *word = argv[6];
it should be const char*

2021-10-05 10:35 UTC, aloknigam247 commented on Utkarsh/wcomp/main.c
> +            if (argv[5] == "strict")
strings are not compared this way

2021-10-05 12:08 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/main.c
> +            char *word = argv[6];
okay

2021-10-05 12:08 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/main.c
> +            if (argv[5] == "strict")
corrected

2021-10-13 16:48 UTC, aloknigam247 requested changes

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/linklist.c
> +        printf("%s ", temp->data);
\n is needed to print lines in new line.

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/linklist.c
> +void printlink(struct Node *head)
use this function in main.c

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/pattern.c
> +    char *line;
line should NULL

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/strict.c
> +    char *line;
line should be null

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/strict.c
> +        char *match = malloc(sizeof(char) * (strlen(word) + 1));
why do we need match now when we have complete line

2021-10-13 16:48 UTC, aloknigam247 commented on Utkarsh/wcomp/linklist.c
> +#include"link.h"
change file name to linklist.h

2021-10-13 17:50 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/linklist.c
> +#include"link.h"
Done

2021-10-13 17:50 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/pattern.c
> +    char *line;
Done

2021-10-13 17:50 UTC, utkarshtyagi2 commented on Utkarsh/wcomp/linklist.c
> +        printf("%s ", temp->data);
Done

2021-10-14 07:41 UTC, aloknigam247 commented on Utkarsh/wcomp/strict.c
> +        char *match = malloc(sizeof(char) * (strlen(word) + 1));
now i read each line 2 times, one for match and other to store line. If I already have complete line, I think we should skip reading  match and use line to find whether its a match or not. This will improve our worst case time complexity and space complexity too.

2021-11-16 08:14 UTC, merged