Abhishek pascal string
PinE-academy/DV_6_C_CPP pull request #8
Opened 2021-09-28 11:33 UTC by Abhishek08Mi

2021-10-08 13:51 UTC, aloknigam247 requested changes

2021-10-08 13:51 UTC, aloknigam247 commented on abhishek/pascal_string/Makefile
> +	rm -rf *.exe P_string_output
what do we need to clear .exe here ?

2021-10-08 13:51 UTC, aloknigam247 commented on abhishek/pascal_string/Makefile
> +Driver.o: Driver.c
use main.c as driver

2021-10-08 13:51 UTC, aloknigam247 commented on abhishek/pascal_string/Makefile
> +P_string_output: p_string.o Driver.o
program name should be demo

2021-10-08 15:43 UTC, Abhishek08Mi commented on abhishek/pascal_string/Makefile
> +P_string_output: p_string.o Driver.o
Sir Program name means target?

2021-10-08 15:43 UTC, Abhishek08Mi commented on abhishek/pascal_string/Makefile
> +Driver.o: Driver.c
Sir instead of driver.o i should take main.o?

2021-10-09 17:43 UTC, aloknigam247 requested changes

2021-10-09 17:43 UTC, aloknigam247 commented on abhishek/pascal_string/Makefile
> +	gcc -c Driver.c
Driver.c ?

2021-11-16 16:26 UTC, merged